// SPDX-License-Identifier: MIT-0
// Copyright 2026 Abacus.AI, Inc. MIT No Attribution: you may use, copy, modify
// and distribute this file without restriction or attribution. Provided "as is",
// without warranty of any kind.

// SimlessKit: headless render host for the `simless` CLI.
// Generated by `simless init`. Do not edit; `simless init --force` rewrites it.
//
// DEBUG-only and inert unless the app is launched with `--simless-port <n>`
// (which only `simless` does). Then it hides the app (no window, no Dock icon),
// serves render requests over 127.0.0.1, and hot-loads patch dylibs that `simless`
// compiles from edited view files.
#if DEBUG && os(iOS)
import SwiftUI
import UIKit
import Network

/// Fixtures are registered by `simlessFixtures(_:)` in SimlessFixtures.swift.
@MainActor
public final class SimlessRegistry {
    public private(set) var names: [String] = []
    private var makers: [String: () -> AnyView] = [:]

    public init() {}

    /// Registers a screen in a deterministic state. Later registrations of the
    /// same name replace earlier ones.
    public func add<V: View>(_ name: String, _ make: @escaping () -> V) {
        if makers[name] == nil { names.append(name) }
        makers[name] = { AnyView(make()) }
    }

    func make(_ name: String) -> AnyView? { makers[name]?() }
}

@MainActor
enum SimlessHost {
    /// True when this process is a `simless` render host. Apps can use it to skip
    /// side effects (analytics, network sync) that a render host should not do.
    static var isActive: Bool { ProcessInfo.processInfo.arguments.contains("--simless-port") }

    private static var registry = SimlessRegistry()
    private static var patchGeneration = 0
    private static var renders = 0
    private static var listener: NWListener?
    private static var window: UIWindow?
    private static var lastRequest = Date()
    /// Exit after this long without requests, so a forgotten host never lingers.
    private static var idleLimit: TimeInterval = 1800

    /// Call once from `App.init()`. No-op unless launched by `simless`.
    static func startIfRequested() {
        let args = ProcessInfo.processInfo.arguments
        let port = args.firstIndex(of: "--simless-port").flatMap { i in i + 1 < args.count ? UInt16(args[i + 1]) : nil }
        // simless also launches the app to install it and to run unit tests;
        // those runs set SIMLESS_HEADLESS so they never show a window either.
        let launchedBySimless = port != nil || ProcessInfo.processInfo.environment["SIMLESS_HEADLESS"] == "1"
        guard launchedBySimless else { return }
        if ProcessInfo.processInfo.isiOSAppOnMac {
            // No window may reach the screen: suppress ordering before the first
            // window exists, hide, and hide again whenever one appears.
            suppressWindowOrdering()
            goHeadless()
            NotificationCenter.default.addObserver(forName: UIWindow.didBecomeVisibleNotification, object: nil,
                                                   queue: .main) { _ in MainActor.assumeIsolated { goHeadless() } }
        }
        guard let port else { return }
        if let j = args.firstIndex(of: "--simless-idle"), j + 1 < args.count, let s = TimeInterval(args[j + 1]) {
            idleLimit = s
        }
        // After launch completes, so NSApplication and the scene exist.
        DispatchQueue.main.async { MainActor.assumeIsolated { start(port: port) } }
    }

    private static func start(port: UInt16) {
        goHeadless()
        removeStalePatches()
        Timer.scheduledTimer(withTimeInterval: 60, repeats: true) { _ in
            MainActor.assumeIsolated { if Date().timeIntervalSince(lastRequest) > idleLimit { exit(0) } }
        }
        enableAccessibilityAutomation()
        simlessFixtures(registry)
        loadBundledPatch()
        let frame = CGRect(x: 0, y: 0, width: 402, height: 874)
        if ProcessInfo.processInfo.isiOSAppOnMac {
            let w = UIWindow(frame: frame)
            w.isHidden = false
            window = w
        } else if let scene = UIApplication.shared.connectedScenes.compactMap({ $0 as? UIWindowScene }).first {
            // In a simulator (`simless calibrate`): a real scene window, so the
            // device's own safe areas and traits apply.
            let w = UIWindow(windowScene: scene)
            w.frame = frame
            w.windowLevel = .alert + 1
            w.makeKeyAndVisible()
            window = w
        }
        do {
            let params = NWParameters.tcp
            params.requiredLocalEndpoint = .hostPort(host: "127.0.0.1", port: NWEndpoint.Port(rawValue: port)!)
            params.allowLocalEndpointReuse = true
            let l = try NWListener(using: params)
            l.newConnectionHandler = { conn in Task { @MainActor in serve(conn) } }
            l.start(queue: .main)
            listener = l
        } catch {
            exit(75)   // port unavailable: let `simless` notice and retry elsewhere
        }
    }

    // MARK: - Protocol: newline-delimited JSON

    private struct Request: Decodable {
        let cmd: String
        var fixture: String?
        var style: String?
        var width: Double?
        var height: Double?
        var safeTop: Double?       // emulated safe area (Mac only; a simulator has real ones)
        var safeBottom: Double?
        var image: Bool?
        var file: String?
    }

    private struct Node: Encodable {
        let role: String?
        let label: String?
        let value: String?
        let id: String?
        let frame: [Double]
    }

    private struct Traits: Encodable {
        let horizontalSizeClass: String
        let verticalSizeClass: String
        let idiom: String          // what the view's trait collection reports
        let deviceIdiom: String    // UIDevice.current.userInterfaceIdiom (can't be overridden)
        let safeArea: [Double]     // top, left, bottom, right
        let onMac: Bool
    }

    private struct Response: Encodable {
        var ok = true
        var error: String?
        var pid: Int32?
        var tmp: String?
        var fixtures: [String]?
        var patch: Int?
        var renders: Int?
        var footprintMB: Double?
        var fixture: String?
        var renderMs: Double?
        var nodes: [Node]?
        var png: String?
        var loadMs: Double?
        var traits: Traits?
    }

    private static func serve(_ conn: NWConnection) {
        conn.start(queue: .main)
        var buffer = Data()
        func receive() {
            conn.receive(minimumIncompleteLength: 1, maximumLength: 1 << 20) { data, _, done, err in
                if let data { buffer.append(data) }
                Task { @MainActor in
                    while let nl = buffer.firstIndex(of: 0x0A) {
                        let line = buffer[buffer.startIndex..<nl]
                        buffer.removeSubrange(buffer.startIndex...nl)
                        let (response, after) = handle(Data(line))
                        var out = (try? JSONEncoder().encode(response)) ?? Data("{\"ok\":false}".utf8)
                        out.append(0x0A)
                        conn.send(content: out, completion: .contentProcessed { _ in after?() })
                    }
                    if done || err != nil { conn.cancel() } else { receive() }
                }
            }
        }
        receive()
    }

    private static func handle(_ line: Data) -> (Response, (() -> Void)?) {
        lastRequest = Date()
        guard let req = try? JSONDecoder().decode(Request.self, from: line) else {
            return (Response(ok: false, error: "bad request"), nil)
        }
        switch req.cmd {
        case "stats":
            return (Response(pid: getpid(), tmp: FileManager.default.temporaryDirectory.path,
                             fixtures: registry.names, patch: patchGeneration, renders: renders,
                             footprintMB: footprintMB()), nil)
        case "render":
            return (render(req), nil)
        case "load":
            return (load(req), nil)
        case "stop":
            // Reply first, then exit.
            return (Response(), { exit(0) })
        default:
            return (Response(ok: false, error: "unknown cmd \(req.cmd)"), nil)
        }
    }

    // MARK: - Rendering

    private static func render(_ req: Request) -> Response {
        guard let name = req.fixture, let view = registry.make(name), let window else {
            return Response(ok: false, error: "unknown fixture '\(req.fixture ?? "")'", fixtures: registry.names)
        }
        let start = CFAbsoluteTimeGetCurrent()
        let rect = CGRect(x: 0, y: 0, width: req.width ?? 402, height: req.height ?? 874)
        window.frame = rect
        let host = UIHostingController(rootView: view)
        host.overrideUserInterfaceStyle = req.style == "dark" ? .dark : .light
        // The hidden window lands on whichever display macOS picks; pin the
        // scale so layout rounding (and PNGs) don't depend on that display.
        host.traitOverrides.displayScale = 2
        // An iOS app on a Mac reports iPad-like traits; give phone canvases a
        // phone's traits and, on the Mac, the device's safe areas (notch, home
        // indicator). A simulator already has the real ones.
        let phone = rect.width < 600
        host.traitOverrides.horizontalSizeClass = phone ? .compact : .regular
        host.traitOverrides.verticalSizeClass = .regular
        host.traitOverrides.userInterfaceIdiom = phone ? .phone : .pad
        if ProcessInfo.processInfo.isiOSAppOnMac {
            host.additionalSafeAreaInsets = UIEdgeInsets(top: req.safeTop ?? 0, left: 0, bottom: req.safeBottom ?? 0, right: 0)
        }
        window.rootViewController = host
        host.view.frame = rect
        host.view.layoutIfNeeded()
        // One frame for SwiftUI to commit, then lay out again.
        RunLoop.main.run(until: Date().addingTimeInterval(0.016))
        host.view.layoutIfNeeded()

        let nodes = collect(host.view)
        var png: String?
        if req.image == true {
            let format = UIGraphicsImageRendererFormat()
            format.scale = 2
            let img = UIGraphicsImageRenderer(bounds: rect, format: format).image { _ in
                host.view.drawHierarchy(in: rect, afterScreenUpdates: true)
            }
            png = img.pngData()?.base64EncodedString()
        }
        renders += 1
        goHeadless()
        let tc = host.traitCollection, insets = host.view.safeAreaInsets
        func sizeClass(_ s: UIUserInterfaceSizeClass) -> String { s == .compact ? "compact" : s == .regular ? "regular" : "unspecified" }
        func idiom(_ i: UIUserInterfaceIdiom) -> String {
            switch i { case .phone: "phone"; case .pad: "pad"; case .mac: "mac"; default: "other" }
        }
        var r = Response(patch: patchGeneration, fixture: name,
                         renderMs: (CFAbsoluteTimeGetCurrent() - start) * 1000, nodes: nodes, png: png)
        r.traits = Traits(horizontalSizeClass: sizeClass(tc.horizontalSizeClass), verticalSizeClass: sizeClass(tc.verticalSizeClass),
                          idiom: idiom(tc.userInterfaceIdiom), deviceIdiom: idiom(UIDevice.current.userInterfaceIdiom),
                          safeArea: [insets.top, insets.left, insets.bottom, insets.right].map { Double($0) },
                          onMac: ProcessInfo.processInfo.isiOSAppOnMac)
        return r
    }

    // MARK: - Accessibility tree

    /// SwiftUI only vends its accessibility tree to an active assistive client;
    /// automation mode turns that on in-process (the approach KIF uses).
    private static func enableAccessibilityAutomation() {
        guard let h = dlopen("/usr/lib/libAccessibility.dylib", RTLD_NOW),
              let sym = dlsym(h, "_AXSSetAutomationEnabled") else { return }
        typealias Fn = @convention(c) (Bool) -> Void
        unsafeBitCast(sym, to: Fn.self)(true)
    }

    private static func collect(_ root: UIView) -> [Node] {
        var out: [Node] = []
        var seen = Set<ObjectIdentifier>()
        // accessibilityFrame is in screen space; frames are reported relative to the host view.
        let origin = root.accessibilityFrame.origin
        func visit(_ obj: NSObject, depth: Int) {
            guard depth < 80, seen.insert(ObjectIdentifier(obj)).inserted else { return }
            if obj.isAccessibilityElement {
                let a = obj.accessibilityFrame
                let id = obj.responds(to: NSSelectorFromString("accessibilityIdentifier"))
                    ? obj.value(forKey: "accessibilityIdentifier") as? String : nil
                out.append(Node(role: role(obj.accessibilityTraits), label: obj.accessibilityLabel,
                                value: obj.accessibilityValue, id: (id?.isEmpty ?? true) ? nil : id,
                                frame: [a.minX - origin.x, a.minY - origin.y, a.width, a.height]
                                    .map { (Double($0) * 10).rounded() / 10 }))
            }
            var children: [NSObject] = []
            if let elements = obj.accessibilityElements as? [NSObject] {
                children += elements
            } else {
                let n = obj.accessibilityElementCount()
                if n != NSNotFound && n > 0 {
                    for i in 0..<n { if let e = obj.accessibilityElement(at: i) as? NSObject { children.append(e) } }
                }
            }
            if let view = obj as? UIView { children += view.subviews }
            for c in children { visit(c, depth: depth + 1) }
        }
        visit(root, depth: 0)
        return out
    }

    private static func role(_ t: UIAccessibilityTraits) -> String {
        if t.contains(.button) { return "button" }
        if t.contains(.link) { return "link" }
        if t.contains(.searchField) { return "search" }
        if t.contains(.header) { return "header" }
        if t.contains(.image) { return "image" }
        if t.contains(.adjustable) { return "adjustable" }
        if t.contains(.staticText) { return "text" }
        return "element"
    }

    // MARK: - Hot reload

    /// A patch dylib exports `simless_patch_entry(registry)`, which runs the patch's
    /// own copy of `simlessFixtures`, so every fixture is rebuilt from the
    /// edited view code.
    private typealias PatchEntry = @convention(c) (UnsafeMutableRawPointer) -> Void

    private static func apply(_ path: String) -> String? {
        // dlopen of quarantined code blocks on a Gatekeeper prompt, which would
        // hang a headless host. `simless` never produces quarantined patches; refuse
        // rather than hang if one appears anyway.
        if getxattr(path, "com.apple.quarantine", nil, 0, 0, 0) >= 0 {
            return "patch is quarantined; refusing to load"
        }
        guard let handle = dlopen(path, RTLD_NOW | RTLD_LOCAL) else {
            return "dlopen: " + String(cString: dlerror())
        }
        guard let sym = dlsym(handle, "simless_patch_entry") else { return "patch has no simless_patch_entry" }
        let fresh = SimlessRegistry()
        unsafeBitCast(sym, to: PatchEntry.self)(Unmanaged.passUnretained(fresh).toOpaque())
        registry = fresh
        patchGeneration += 1
        return nil
    }

    /// Live: `simless` (via SimlessAgent) placed the patch in our tmp dir.
    private static func load(_ req: Request) -> Response {
        guard let file = req.file, !file.contains("/") else {
            return Response(ok: false, error: "load needs a file name")
        }
        let start = CFAbsoluteTimeGetCurrent()
        let path = FileManager.default.temporaryDirectory.appendingPathComponent(file).path
        if let error = apply(path) { return Response(ok: false, error: error) }
        unlink(path)   // the code stays mapped; the file is no longer needed
        return Response(patch: patchGeneration, loadMs: (CFAbsoluteTimeGetCurrent() - start) * 1000)
    }

    /// Live patches left over from a previous host process.
    private static func removeStalePatches() {
        let tmp = FileManager.default.temporaryDirectory
        for f in (try? FileManager.default.contentsOfDirectory(atPath: tmp.path)) ?? []
        where f.hasPrefix("SimlessPatch") && f.hasSuffix(".dylib") {
            try? FileManager.default.removeItem(at: tmp.appendingPathComponent(f))
        }
    }

    /// Warm: the patch was installed inside the app bundle (never quarantined).
    private static func loadBundledPatch() {
        let dir = Bundle.main.bundleURL.appendingPathComponent("SimlessPatches")
        let newest = ((try? FileManager.default.contentsOfDirectory(atPath: dir.path)) ?? [])
            .filter { $0.hasSuffix(".dylib") }.sorted().last
        if let newest { _ = apply(dir.appendingPathComponent(newest).path) }
    }

    // MARK: - Headless

    /// Reaches the AppKit NSApplication underneath the iOS app: no Dock icon,
    /// never active, windows hidden. Rendering is unaffected.
    private static func goHeadless() {
        guard let cls = NSClassFromString("NSApplication") as? NSObject.Type,
              let app = cls.value(forKey: "sharedApplication") as? NSObject else { return }
        let setPolicy = NSSelectorFromString("setActivationPolicy:")
        typealias PolicyFn = @convention(c) (AnyObject, Selector, Int) -> Bool
        _ = unsafeBitCast(app.method(for: setPolicy), to: PolicyFn.self)(app, setPolicy, 2)  // .prohibited
        app.perform(NSSelectorFromString("hide:"), with: nil)
        // Belt and braces: a window ordered in before `hide:` takes effect stays
        // fully transparent and click-through. Rendering doesn't depend on it.
        typealias FloatFn = @convention(c) (AnyObject, Selector, CGFloat) -> Void
        typealias BoolFn = @convention(c) (AnyObject, Selector, Bool) -> Void
        let alpha = NSSelectorFromString("setAlphaValue:"), ignore = NSSelectorFromString("setIgnoresMouseEvents:")
        for w in (app.value(forKey: "windows") as? [NSObject]) ?? [] {
            unsafeBitCast(w.method(for: alpha), to: FloatFn.self)(w, alpha, 0)
            unsafeBitCast(w.method(for: ignore), to: BoolFn.self)(w, ignore, true)
        }
    }

    /// Makes AppKit's window-ordering calls no-ops for this process, so the
    /// app's own windows never appear on screen. Rendering draws off-screen and
    /// doesn't need them.
    private static func suppressWindowOrdering() {
        let noOp1: @convention(block) (AnyObject) -> Void = { _ in }
        let noOpSender: @convention(block) (AnyObject, AnyObject?) -> Void = { _, _ in }
        let noOpOrder: @convention(block) (AnyObject, Int, Int) -> Void = { _, _, _ in }
        let replacements: [(String, AnyObject)] = [
            ("orderWindow:relativeTo:", unsafeBitCast(noOpOrder, to: AnyObject.self)),
            ("orderFront:", unsafeBitCast(noOpSender, to: AnyObject.self)),
            ("makeKeyAndOrderFront:", unsafeBitCast(noOpSender, to: AnyObject.self)),
            ("orderFrontRegardless", unsafeBitCast(noOp1, to: AnyObject.self)),
        ]
        for name in ["NSWindow", "UINSWindow"] {
            guard let cls = NSClassFromString(name) else { continue }
            for (sel, block) in replacements {
                if let m = class_getInstanceMethod(cls, NSSelectorFromString(sel)) {
                    method_setImplementation(m, imp_implementationWithBlock(block))
                }
            }
        }
    }

    private static func footprintMB() -> Double {
        var info = task_vm_info_data_t()
        var count = mach_msg_type_number_t(MemoryLayout<task_vm_info_data_t>.size / MemoryLayout<natural_t>.size)
        let kr = withUnsafeMutablePointer(to: &info) {
            $0.withMemoryRebound(to: integer_t.self, capacity: Int(count)) {
                task_info(mach_task_self_, task_flavor_t(TASK_VM_INFO), $0, &count)
            }
        }
        return kr == KERN_SUCCESS ? (Double(info.phys_footprint) / 1_048_576 * 10).rounded() / 10 : -1
    }
}
#endif
